### ISSUE TITLE
Consulta covid - Escopo contratos emergenciais

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#18]
# Legislação relevante

## [Lei 13.979, de 06/02/2020](http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2020/lei/L13979.htm#art4)

> Art. 4º  É dispensável a licitação para aquisição de bens, serviços, inclusive de engenharia, e insumos destinados ao enfrentamento da emergência de saúde pública de importância internacional decorrente do coronavírus de que trata esta Lei.
>
> [...]
>
> § 2º  Todas as contratações ou aquisições realizadas com fulcro nesta Lei serão imediatamente disponibilizadas em sítio oficial específico na rede mundial de computadores (internet), contendo, no que couber, além das informações previstas no § 3º do art. 8º da Lei nº 12.527, de 18 de novembro de 2011, o nome do contratado, o número de sua inscrição na Receita Federal do Brasil, o prazo contratual, o valor e o respectivo processo de contratação ou aquisição.

## [Lei 23.640, de 14/05/2020](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=LEI&num=23640&comp=&ano=2020&aba=js_textoOriginal#texto)

> Art. 1º – Os órgãos e entidades da administração pública estadual publicarão, no Portal da Transparência do Estado de Minas Gerais, relação dos contratos, convênios e parcerias celebrados em caráter emergencial em razão do estado de calamidade pública decorrente da pandemia de Covid-19.

**Comment by fjuniorr** [comment]
Tanto as [recomendações da Transparência internacional](https://comunidade.transparenciainternacional.org.br/asset/86:tibr-recomendacoes-de-contratacoes-emergenciais-covid19?stream=1)

![image](https://user-images.githubusercontent.com/4969445/82821366-5ce60a80-9e7a-11ea-8450-f4c79c3e0ed9.png)

quanto a legislação relevante possuem enfoque nas contratações emergenciais. @silviana-faria [encontrou] em 20/05 20 processos realizados com fulcro na Lei Federal n. 13.979/2020 que não possuem execução no Programa 26.

**Comment by silviana-faria** [comment]
Exemplos de Processos
 * [0500005 000009/2020](http://transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2020/20200101/20201231/319179)

* [1501561 000010/2020](http://transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2020/20200101/20201231/321142).

* [0250073 000002/2020](http://transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2020/20200101/20201231/322110) - Não houve nenhuma execução

No dia, 25/05, dos 50 processos emergenciais publicados no Portal de Dados Abertos 26, até o momento, não possuem execução no Programa 26.

[Relação do Processos emergenciais vs programas de execução](https://trello.com/c/SoaO26T2/479)

**Comment by soraiadias** [comment]
Na reunião com a SEPLAG confirmamos que não há um campo que identifique se a contração foi realizada em caráter emergencial. A solicitação nesse caso, seria a criação de "um campo" que possibilite essa identificação.

**Comment by fjuniorr** [comment]
As contratações ou aquisições que não forem celebradas por meio de dispensa, mas utilizaram ritos diferenciados previstos na Lei 13.979/2020, como [redução dos prazos pela metade de pregão](http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2020/lei/L13979.htm#art4g), devem ser divulgados.
