### ISSUE TITLE
Consulta covid - Informações desejáveis

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#19]
Estão disponíveis no Armazém de Compras e, assim como #13, podem ser inseridas no [conjunto de dados](http://www.transparencia.dadosabertos.mg.gov.br/dataset/contratacoes-coronavirus) atual, possivelmente como novos recursos para melhor organização, as seguintes variáveis

* Data de celebração
* Edital
* Forma/modalidade da contratação

A disponibilidade das variáveis 

* Local da Execução
* Fases da licitação

Dependem de interpretação da natureza das mesmas.

**Comment by fjuniorr** [comment]
Algumas dúvidas:

* A grande maioria dos processos não vai possuir edital, mas podemos inserir link para a seção;
* Qual a expectativa em relação a "fases da licitação"?

**Comment by silviana-faria** [comment]
Não localizei no armazém de dados nada sobre as fases da licitação.

Dúvida:
A Transparência Internacional fala em fases da licitação apenas na modalidade pregão.

![image](https://user-images.githubusercontent.com/53793354/82900099-659a1780-9f32-11ea-8f5d-b54cbb3e6819.png)

**Comment by silviana-faria** [comment]
Quanto ao local de execução o Portal de Transparência divulga a Cidade de entrega. O processo de compra disponível no Portal de Compras apresenta o endereço na entrega do item.

Não localizei esse dado no armazém.

![image](https://user-images.githubusercontent.com/53793354/82906643-ef021780-9f3b-11ea-940a-4935fc03f9a6.png)
