### ISSUE TITLE
Consulta covid - Íntegra do contrato em formato aberto

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#21]
# Legislação relevante

## [Lei 12.527, de 18/11/2011](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm#art8)

> Art. 8º É dever dos órgãos e entidades públicas promover, independentemente de requerimentos, a divulgação em local de fácil acesso, no âmbito de suas competências, de informações de interesse coletivo ou geral por eles produzidas ou custodiadas.
> 
> § 1º Na divulgação das informações a que se refere o caput, deverão constar, no mínimo:
> 
> [...]
> 
> IV - informações concernentes a procedimentos licitatórios, inclusive os respectivos editais e resultados, bem como a todos os contratos celebrados

## [Lei 23569, DE 13/01/2020](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=LEI&num=23569&comp=&ano=2020)

> Art. 2º – Serão publicados no site do ente ou do órgão estatal responsável, logo após o encerramento do processo licitatório, o resumo das propostas de todos os licitantes, notadamente a parte relativa a preços e prazos, e, logo após sua assinatura, o termo do contrato celebrado e __seus eventuais termos aditivos ou modificativos.__

## [ACÓRDÃO TCU 1855/2018 – PLENÁRIO](https://pesquisa.apps.tcu.gov.br/#/redireciona/acordao-completo/%22ACORDAO-COMPLETO-2291556%22)

> 9.3. recomendar ao Ministério da Transparência e Controladoria-Geral da União, com
fundamento no art. 250, III, do Regimento Interno do TCU, que possibilite a inserção de arquivos com o inteiro teor dos contratos administrativos, seus anexos e aditivos nas páginas de transparência dos órgãos, com o intuito de aprimorar a transparência ativa e em atendimento aos fins do art. 8º, §1º, IV, da Lei 12.527/2011;

**Comment by fjuniorr** [comment]
Como as recomendações da Transparência Internacional fizeram menção a [Open Contracting
Partnership](https://www.open-contracting.org/), achei que a pontuação 1 (disponível em formatos abertos) no item "Possibilidade de download da íntegra do contrato" estava reservada para os entes que estivem realizando a publicação dos dados de contratos de acordo com o [Open Contracting Data Standard](https://standard.open-contracting.org/latest/en/).

No entanto, ao avaliar a [base de dados da primeira avaliação](https://comunidade.transparenciainternacional.org.br/asset/88:tibr-basededadosrecomendacoescovid19), essa hipótese foi descartada, tendo em vista a pontuação dos estados:

![image](https://user-images.githubusercontent.com/4969445/82826463-95d6ad00-9e83-11ea-9a80-91b5432664a5.png)

Exemplo: [Painel ES](https://coronavirus.es.gov.br/contratos-emergenciais)

Ps. O MPRJ está [divulgando dados](https://github.com/mp-rj/Impacta/blob/master/LEIAME.md) de um contrato no formato OCDS e descreveu a experiência [aqui](https://medium.com/inova%C3%A7%C3%A3o-em-governo-e-no-controle/levando-transpar%C3%AAncia-a-s%C3%A9rio-e4baa0b52fa3). É um introdução interessante para quem não conhece o assunto.

**Comment by silviana-faria** [comment]
A Transparência Internacional orienta quanto a divulgação da nota de empenho. Acredito que na ausência de contrato seja interessante publicar a Nota de Empenho ou a Autorização de Compra.

![image](https://user-images.githubusercontent.com/53793354/82902868-7fd5f480-9f36-11ea-85f1-f37ec5b619cd.png)

O [art. 62 da Lei Federal 8.666/93] (htp://www.planalto.gov.br/ccivil_03/Leis/L8666cons.htm#art62) estabelece que em casos específicos o contrato pode ser substituído por outros instrumentos hábeis, tais como Nota de Empenho e Autorização de Compra. Assim, como esses instrumentos são equivalentes ao Contrato devem ser disponibilizados.

**Comment by silviana-faria** [comment]
Exemplos de Publicação de [Ordem de Fornecimento](https://coronavirus.es.gov.br/Media/Coronavirus/Transparencia/ContratosEmergenciais/OF%20044%202020%20ASSINADA%20VERONA%20-%20M%C3%81SCARA%20DE%20TECIDO%20-%202020%203M3Z1.pdf) relativo a Contratos Emergenciais no ES.

**Comment by silviana-faria** [comment]
Em todos os estados pesquisados nenhuma publicação está em formato aberto (.txt ou .doc). No entanto, a maioria publica além do contrato na íntegra outros documentos, como: termo de referência, projeto básico

Estados que tiraram nota máxima na primeira avaliação:

* __[Espírito Santo](https://coronavirus.es.gov.br/contratos-emergenciais)__:
       Contrato em PDF + Termo de Referência/Projeto Básico

* __[Distrito Federal](http://www.coronavirus.df.gov.br/index.php/contratacoes/)__
   Contrato em PDF + Projeto Básico + Proposta Empresa
* __[Ceará]()__
   Contrato PDF (quando existe) + [Documento de Processo de Dispensa de Liciação](https://sacc.cge.ce.gov.br/UploadArquivos/20200415.1123415.Declaracao.Dispensa.DESPESA.SEM.INSTRUMENTO.CONTRATUAL.pdf) + [Edital de Licitaçao](https://sacc.cge.ce.gov.br/UploadArquivos/20200415.1123415.Declaracao.Dispensa.DESPESA.SEM.INSTRUMENTO.CONTRATUAL.pdf) + página url com os dados da compra 

* __[Sergipe](https://www.saude.se.gov.br/?page_id=39911)__
    Contrato PDF
