### ISSUE TITLE
Consulta covid - Informações desejáveis - Local da execução

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#23]
Vide https://github.com/transparencia-mg/especificacoes-portal-transparencia/issues/19#issuecomment-634027227

**Comment by silviana-faria** [comment]
O Estados que tiraram nota máxima na primeira avaliação foram:

* __[Maranhão](http://www.transparencia.ma.gov.br/app/compras/covid#lista): Local de execução - apenas a cidade__

![image](https://user-images.githubusercontent.com/53793354/83751899-00cf7300-a63e-11ea-9e53-9f78324c26c7.png)

* __[Santa Catarina](http://www.transparencia.sc.gov.br/contratos/extratosigef?gestaofiltro%5B%5D=1&unidadegestorafiltro%5B%5D=440001&nucontratofiltro%5B%5D=2020CT001115): Local de execução - Nome do órgão__

![image](https://user-images.githubusercontent.com/53793354/83753123-1776c980-a640-11ea-85c7-0ab391a8aad3.png)

* __[Macéio](http://www.licitacao.maceio.al.gov.br/visualizar/1700): o local de execução está no termo de referência__

Outros estados que implementaram o campos após a avaliação:

* __[Distrito Federal](): Local de execução - Nome ou unidade do órgão__

![image](https://user-images.githubusercontent.com/53793354/83753516-d3d08f80-a640-11ea-9124-f33bc3648435.png)

![image](https://user-images.githubusercontent.com/53793354/83753551-e34fd880-a640-11ea-919d-9909e4d4bbc9.png)

* __[Espírito Santo](https://coronavirus.es.gov.br/contratos-emergenciais) - Local de execução: Endereço Completo__

![image](https://user-images.githubusercontent.com/53793354/83753809-548f8b80-a641-11ea-9183-4cf2bae6ac4d.png)
