### ISSUE TITLE
Consulta covid - Informações desejáveis - Fases da licitação

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#24]
Vide issue #19

**Comment by silviana-faria** [comment]
* Espírito Santo:  __[Histórico do processo](https://processoeletronico.es.gov.br/?protocolo=2020-5CWTV)__

![image](https://user-images.githubusercontent.com/53793354/83755083-68d48800-a643-11ea-961b-cd28a2196419.png)

* [Ceará](https://cearatransparente.ce.gov.br/portal-da-transparencia/contratos/contratos/337833?locale=pt-BR): __[Documento de processo de licitação](https://sacc.cge.ce.gov.br/UploadArquivos/20200415.1123415.Declaracao.Dispensa.DESPESA.SEM.INSTRUMENTO.CONTRATUAL.pdf)__

**Comment by silviana-faria** [comment]
Dados da [2ª avaliação]()

* **Espírito Santo:** Possui uma link específico sobre o item [Edital e fases da licitação](https://transparencia.es.gov.br/Compras?Filtro.TipoConsultaSelecionado=2&Filtro.OrgaoSelecionado=0&Filtro.AnoSelecionado=2020&Filtro.PeriodoSelecionado=1&Filtro.DataInicioSelecionado=01%2F01%2F2020&Filtro.DataFimSelecionado=31%2F12%2F2020&Filtro.MensalSelecionado=1&Filtro.BimestreSelecionado=1&Filtro.TrimestreSelecionado=1&Filtro.QuadrimestreSelecionado=1&Filtro.SemestreSelecionado=1&Filtro.ModalidadeSelecionado=&Filtro.SituacaoSelecionado=&Filtro.FlagCovid19=true&Filtro.FlagCovid19=false&Filtro.FiltroTextoSelecionado=&busca=1)

![image](https://user-images.githubusercontent.com/53793354/86002056-2dc93880-b9e6-11ea-8a91-5aa95777c064.png)

![image](https://user-images.githubusercontent.com/53793354/86002305-8c8eb200-b9e6-11ea-8e50-816b7a505194.png)

**Comment by silviana-faria** [comment]
Requisito TI - 4ª avaliação

![image](https://user-images.githubusercontent.com/53793354/89810788-018bf600-db14-11ea-9b0c-0f2cbb832f03.png)
