### ISSUE TITLE
Consulta covid - Legislação

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#25]

**Comment by fjuniorr** [comment]
A ALMG tem uma [Central de Monitoramento Coronavírus](https://sites.almg.gov.br/coronavirus/index.html?utm_source=home&utm_medium=megabanner&utm_campaign=coronavirus) com links para as matérias [em tramitação](https://www.almg.gov.br/atividade_parlamentar/tramitacao_projetos/index.html?advanced=advanced&first=false&search=odp&pagina=1&aba=js_tabpesquisaAvancada&txtPalavras=%28pec+ou+pl+ou+plc+ou+pre%29.prop.+e+tramitacao.domi.+e+coronavirus.obse.&txtEmTram=on&txtTramEnc=on) e as [leis aprovadas](https://sites.almg.gov.br/coronavirus/acoes-almg/leis-aprovadas.html)

![image](https://user-images.githubusercontent.com/4969445/83064000-754f5400-a037-11ea-9e1e-2839e51691b3.png)

Acho que podemos fazer esse redirecionamento também.

**Comment by silviana-faria** [comment]
## Requisito - 4ª avaliação 

![image](https://user-images.githubusercontent.com/53793354/89782428-a80fd100-daeb-11ea-8fd2-ed9a79364925.png)

**Comment by silviana-faria** [comment]
Conforme alinhado com a Subcontroladora foi incluído os temas no Portal de Transparência. [Portal da Transparência - Legislação](http://transparencia.mg.gov.br/covid-19/legislacao-e-normativos)
