### ISSUE TITLE
17. Número/ano dos processos de seleção pública para contratação temporária relacionados a COVID

### ISSUE THREAD

**Issue by kesiabomfa** [transparencia-mg/especificacoes-portal-transparencia#36]
#### 17. Foi encontrado no portal de transparência o número/ano dos processos de seleção pública para contratação temporária relacionados a COVID?

Resposta

**Itens de verificação 17 e 18 - Divulgação dos processos de seleção pública para contratação temporária e contratos temporários relacionados à COVID**

A consulta da COVID-19 do Portal da Transparência esteve focada na divulgação das contratações de bens e serviços. 
As contratações temporárias de pessoal para enfrentamento da COVID-19 devem ser divulgadas por cada órgão e entidade, por meio da disponibilização em seus próprios sítios eletrônicos, a exemplo da [FHEMIG](http://www.fhemig.mg.gov.br/index.php?option=com_content&view=article&id=1860:chamamento-publico-emergencial&catid=1427:chamamento-publico-emergencial), [UNIMONTES](https://unimontes.br/edital/convocacao-contratacoes-temporarias-para-enfrentamento-do-covid-19/) e [SEJUSP](http://www.seguranca.mg.gov.br/component/gmg/page/3169-ano-2020).

**Comment by kesiabomfa** [comment]
Avaliação: Não

Justificativa: De fato, o Portal da Transparência não contemplou as contratações temporárias para enfrentamento da COVID-19, tendo ficado a carga de cada órgão e entidade a disponibilização em seu próprio sítio eletrônico dos contratos realizados, a exemplo da FHEMIG, UNIMONTES e SEJUSP.

Contudo, visando facilitar a localização dos contratos realizados pelos órgãos e entidades, o Portal da Transparência incluiu um item referente a essas contratações, com links acessíveis a cada órgãos e entidade que utilizou do instituto de contratação temporária de excepcional interesse público para atender as demandas da COVID-19.

**Comment by silviana-faria** [comment]
Sugestão de texto para o Portal de Transparência:

*"Contratações Temporárias de Excepcional Interesse Público: informações sobre as contratações de pessoal realizadas pelo Governo do Estado de Minas Gerais para atender as demandas de enfrentamento a pandemia da COVID-19. Acesse abaixo as contratações realizadas por órgão/entidade:"*

![image](https://user-images.githubusercontent.com/53793354/95330131-7793ab80-087e-11eb-8216-1330ee8f8799.png)
