### ISSUE TITLE
6. A publicação no sítio oficial/ espaço específico contém o prazo contratual

### ISSUE THREAD

**Issue by kesiabomfa** [transparencia-mg/especificacoes-portal-transparencia#37]
#### 6. A publicação no sítio oficial/ espaço específico contém o prazo contratual (§ 2º do art. 4º da Lei 13.979/2020)?

Resposta

**Itens de verificação 6 e 9 - Publicação no sítio oficial/espaço específico contém a íntegra do contrato ou outros instrumentos hábeis e o prazo de vigência contratual**

Quanto aos itens nº 6 e 9, informamos que os dados apresentados no Portal da Transparência do Estado de Minas Gerais refletem na íntegra a bases de dados que alimentam o Portal da Transparência, quais sejam: Sistema Integrado de Administração Financeira e Orçamentária (SIAFI/MG) e Sistema Integrado de Administração de Materiais e Serviços (SIAD) – Módulo Portal de Compras.

No entanto, é sabido que a inexistência de prazo contratual e de contratos se deve a dois principais motivos, os quais se destacam:

a) Processos de compras com entrega imediata e integral: Esse tipo de contratação por não resultarem obrigações futuras estão dispensadas do "Termo de Contrato" nos termos do §4º, art 62 da Lei 8.666/93. Nesse sentido, esses processos não possuem número de contrato no Sistema SIAD e, portanto, não possuem prazo contratual (início e fim de vigência contratual).
Para estes casos, a Nota de Empenho é o documento hábil que ampara a obrigação de efetuar a entrega, sendo que o número e a data do empenho, encontra-se disponível no ícone clícavel do Número do Processo de Compra.

b) O segundo caso, contemplam os processos de compras com entrega parcelada, cujos contratos ainda não foram assinados.
A despeito desses dois fatores, situações excepcionais podem ocorrer nos órgãos e entidades em processos de compra específicos. 

Nesses casos, como por exemplo a inexistência contratual referente ao processo de compras 0250073 000003/2020 apontada no Relatório de Acompanhamento, é necessário o envio de questionamento à Polícia Militar do Estado de Minas Gerais, órgão responsável pela contratação, para esclarecimentos adicionais.

**Comment by silviana-faria** [comment]
Foi realizado uma conferência no módulo Portal de Compras - BO para verificar se os processos de compras que estão disponíveis no Portal realmente não possuem número de contrato. Nessa conferência identificamos que os dados estão conforme a base de dados do BO.
