### ISSUE TITLE
18. Contratos temporários de pessoal relacionados a COVID

### ISSUE THREAD

**Issue by kesiabomfa** [transparencia-mg/especificacoes-portal-transparencia#38]
#### 18. Foi encontrado no portal de transparência os contratos temporários de pessoal relacionados a COVID?

Resposta
Vide #36

**Comment by kesiabomfa** [comment]
Avaliação: Não

Justificativa: De fato, o Portal da Transparência não contemplou as contratações temporárias para enfrentamento da COVID-19, tendo ficado a carga de cada órgão e entidade a disponibilização em seu próprio sítio eletrônico dos contratos realizados, a exemplo da FHEMIG, UNIMONTES e SEJUSP.

Contudo, visando facilitar a localização dos contratos realizados pelos órgãos e entidades, o Portal da Transparência incluiu um item referente a essas contratações, com links acessíveis a cada órgãos e entidade que utilizou do instituto de contratação temporária de excepcional interesse público para atender as demandas da COVID-19.

**Comment by kesiabomfa** [comment]
Contratações Temporárias de Excepcional Interesse Público: informações sobre as contratações de pessoal realizadas pelo Governo do Estado de Minas Gerais para atender as demandas de enfrentamento a pandemia da COVID-19. 
Acesse abaixo as contratações realizadas por órgão/entidade:
- [FHEMIG](http://www.fhemig.mg.gov.br/index.php?option=com_content&view=article&id=1860:chamamento-publico-emergencial&catid=1427:chamamento-publico-emergencial)
- [SEJUSP](http://www.seguranca.mg.gov.br/component/gmg/page/3169-ano-2020)
- [UNIMONTES]()

**Comment by fjuniorr** [comment]
@kesiabomfa o link para a UNIMONTES está incorreto. Não achei no site deles. Você tem a referência correta?

**Comment by silviana-faria** [comment]
@fjuniorr inseri o link da Unimontes
