### ISSUE TITLE
21. Regimes de adiantamento (suprimento de fundos) relacionados a COVID

### ISSUE THREAD

**Issue by kesiabomfa** [transparencia-mg/especificacoes-portal-transparencia#39]
#### 21. Foi encontrado no portal da transparência os regimes de adiantamento (suprimento de fundos) relacionados a COVID?

Resposta:

**Item 21 - Regimes de adiantamento (suprimento de fundos) relacionados à COVID**

O Portal da Transparência não possui mecanismo para identificar as despesas processadas pelo regime de adiantamento destinadas ao enfrentamento da emergência de saúde pública de importância internacional decorrente do coronavírus.

**Comment by kesiabomfa** [comment]
Avaliação: Não

Justificativa: O suprimentos de fundos previsto nos artigos 68 e 69 da Lei nº 4.320/1964 e recentemente para o período da pandemia, previsto no artigo 6º-A da Lei nº 13.979/2020, que englobam despesas que não possam aguardar o tempo necessário para o ciclo normal de licitação ou contratação direta não foi regulamentado pelo Estado de Minas Gerais e portanto este instituto não foi utilizado para compras e contratações para enfrentamento da pandemia provocada pelo coronavírus.

**Comment by fjuniorr** [comment]
O regime de adiantamento foi regulamentado em Minas pelo [Decreto 37924/1996](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=DEC&num=37924&comp=&ano=1996) e alterações:

> DO REGIME ESPECIAL DE ADIANTAMENTO
> 
> Art. 24 – O regime de adiantamento consiste na liberação de numerário para servidor previamente credenciado pelo Ordenador de Despesa, sempre precedido de empenho estimativo na dotação própria, para a realização de despesas que não possam se submeter ao processo normal de pagamento.
> 
> Art. 25 – Somente será permitido o regime de adiantamento para as despesas abaixo mencionadas, observados os seguintes limites para cada adiantamento:

O artigo 6º-A da Lei Federal nº 13.979/2020 apenas estabeleceu limites diferenciados, que, no meu entendimento, se aplicam apenas ao Governo Federal devido a referência ao Cartão de Pagamento.

> Art. 6º-A.  Para a concessão de suprimento de fundos e por item de despesa, e para as aquisições e as contratações a que se refere o caput do art. 4º desta Lei, quando a movimentação for realizada por meio de Cartão de Pagamento do Governo, ficam estabelecidos os seguintes limites:       (Incluído pela Lei nº 14.035, de 2020)
> 
> I – na execução de serviços de engenharia, o valor estabelecido na alínea “a” do inciso I do caput do art. 23 da Lei nº 8.666, de 21 de junho de 1993; e       (Incluído pela Lei nº 14.035, de 2020)
> 
> II – nas compras em geral e em outros serviços, o valor estabelecido na alínea “a” do inciso II do caput do art. 23 da Lei nº 8.666, de 21 de junho de 1993.       (Incluído pela Lei nº 14.035, de 2020)

Levando isso em consideração, e o fato de que o TCE está interessado em adiantamentos relacionados à COVID, acho que não podemos afirmar nada, além de que essa informação não está disponível no Portal da Transparência. 

Além das despesas miúdas de pronto pagamento, um outro exemplo que provavelmente deve ter ocorrido são despesas com transporte urbano (item 3302), que geralmente são processadas pelo regime de adiantamento.

**Comment by kesiabomfa** [comment]
A informação está disponível no portal. Não está disponível na consulta de COVID. Mas é possível consultar as despesas de pronto pagamento.

**Comment by fjuniorr** [comment]
As despesas miúdas de pronto pagamento são um exemplo de despesas que podem ser processadas pelo regime de adiantamento, mas não esgotam as possibilidades.

No fim das contas, a minha conclusão é que o Portal não permite a identificação de quais despesas foram processadas por esse regime.

Acho que [essa cartilha](https://www.gov.br/compras/pt-br/assuntos/combate-ao-covid-19/midias/suprimento-de-fundos.pdf) do governo federal reforça os argumentos que eu fiz acima:

> 07. Na atual conjuntura de calamidade ante a pandemia, o limite de gasto com o suprimento de despesas é diferente?
>
> Como retratado no livreto “Contratação Pública Extraordinária no período do Coronavírius”, “diante do cenário atual de anormalidade e da imperiosidade de uma agilidade para compras, serviços e obras de reparo imediato, a Lei nº 13.979/2020 estipulou os seguintes limites para a concessão de suprimento de fundos e por item de despesa, para as aquisições e contratações mencionadas no artigo 4º da própria lei, quando a movimentação for realizada por meio de Cartão de Pagamento do Governo: (i) até R$ 330.000,00 (trezentos e trinta mil reais) para a execução de serviços de engenharia e (ii) até R$ 176.000,00 (cento e setenta e seis mil reais) para a execução de compras em geral e outros serviços.”
> 
> Desse modo, os valores foram alterados exclusivamente para aquisição de bens, serviços, inclusive de engenharia, e insumos destinados ao enfrentamento da emergência de saúde pública de importância internacional decorrente do coronavírus.
> 
> __Pode-se, por exemplo, contratar um serviço auxiliar de saúde, máscaras, termômetros digitais, sabonete líquido, álcool, ou até mesmo fazer um serviço de reforma em um posto de saúde, até os limites acima. Nessa situação, o suprimento de fundos representa estratégia célere de logística pública, e amplia o poder negocial da Administração Pública.__
> 
> 08. O limite é aplicável aos Estados, Distrito Federal e Municípios?
> 
> Sim, este limite da Lei nº 13.979/2020 é extensível para Estados, Distrito Federal e Municípios alterado exclusivamente para aquisição de bens, serviços, inclusive de engenharia, e insumos destinados ao enfrentamento da emergência de saúde pública de importância internacional decorrente do coronavírus.
> 
> Não é possível que se use o limite da Lei nº 13.979/2020 para despesas estranhas ao enfrentamento da emergência de saúde pública de importância internacional decorrente do coronavírus, ainda que se queira justificar pelo combate à dengue ou qualquer outro motivo de interesse público.
