### ISSUE TITLE
Acordo Judicial Vale - Dados do Convênio / Parceria de saída de Recursos

### ISSUE THREAD

**Issue by silvianafaria** [transparencia-mg/especificacoes-portal-transparencia#53]
Conforme pesquisa no Armazém - SIAFI - Despesa Realizada identificou- se  no campo 'ContratoConvênio Saída' os convênios firmados relacionados com a execução dos recursos vinculados ao Acordo Judicial da Vale.

No entanto, esses convênios não foram localizados no SIGCON- Saída.

![image](https://user-images.githubusercontent.com/53793354/135871119-93ecf617-699f-4fcb-a516-a5a3716d9c21.png)

Dúvidas:
- Qual a classificação dos convênios de saída realizados para a execução do Acordo Judicial da Vale?
- Esses convênios serão executados no SIGCON Saída?
- Se esses convênios não forem executados no SIGCON Saída, onde será possível consultar os dados de execução dos convênios?

**Comment by kesiabomfa** [comment]
Qual a classificação dos convênios de saída realizados para a execução do Acordo Judicial da Vale?
Esses convênios serão executados no SIGCON Saída?
Se esses convênios não forem executados no SIGCON Saída, onde será possível consultar os dados de execução dos convênios?
