### ISSUE TITLE
Erro no Portal - Consulta de Restos a Pagar - retenção

### ISSUE THREAD

**Issue by kesiabomfa** [transparencia-mg/especificacoes-portal-transparencia#56]
Conforme identificado na consulta de Restos a Pagar do Portal da Transparência, a coluna de Valor a Pagar não deduz os valores de retenção ocorridos em restos a pagar.

- CASO CONCRETO: Empenho nº 168/2019 - Controladoria Geral do Estado

**SIAFI**
Conforme se verifica da consulta do SIAFI, foram retidos em 2020 no empenho 168/2019, o valor de R$1.609,92. Restando um valor a ser inscrito em restos a pagar no ano seguinte de R$26.269,83
 
![image](https://user-images.githubusercontent.com/52920939/144617674-3fdb9f64-dffd-4fee-b363-ad8674d42625.png)

![image](https://user-images.githubusercontent.com/52920939/144617707-e520ef8f-665c-43e9-87c3-58460fc1abbb.png)

**PORTAL DA TRANSPARÊNCIA**
Ao trazer essa mesma informação de pagamento na consulta de [Restos a Pagar](https://www.transparencia.mg.gov.br/despesa-estado/restos-a-pagar/restospagar-orgaos/2020/3964/546/42/20/3065/130/58) para o Portal da Transparência, o Portal desconsidera os valores de retenção, e informa para o usuário o Valor a Pagar de R$27.879,75, sem considerar as retenções.
![image](https://user-images.githubusercontent.com/52920939/144617922-5093bce2-56e3-42b1-9157-33a3dbc815de.png)

No ano seguinte, ao informar o Valor Inscrito não Processado, o Portal [Consulta de Restos a Pagar](https://www.transparencia.mg.gov.br/despesa-estado/restos-a-pagar/restospagar-orgaos/2021/4175/546/42/20/3065/130/58) corrige o erro anterior, informando corretamente o valor pago menos as retenções - R$26.289,63.
Dando a impressão ao usuário que ficaram pendentes de pagamento o valor de R$1.609,92.

![image](https://user-images.githubusercontent.com/52920939/144618189-938a5116-5cb3-4c61-958a-e12719897351.png)

- PROCEDIMENTO
Assim, o Portal necessita de uma Manutenção Corretiva no cálculo da coluna Valor a Pagar para incluir os valores de retenção.

**Comment by kesiabomfa** [comment]
#### Retorno do Luiz - em 14/01 por e-mail.

##### Conclusão da análise

A composição atual do campo Valor a Pagar, da consulta de Restos a Pagar, consiste na seguinte fórmula aplicada sobre as colunas exibidas pelo portal:
Valor a Pagar = Valor Inscrito Processado + Valor Inscrito Não Processado – Valor Pago no Ano

Entretanto, conforme observado pela Silviana, valores retidos não estão contidos nas colunas envolvidas na fórmula descrita acima, causando assim uma divergência pontal no caso que foi exemplificado no caso 016520 no Mantis.
Foi solicitado que o cálculo de Valor a Pagar seja realizado conforme fórmula que segue:

Valor a Pagar = Saldo Restos a Pagar processado + Saldo Restos a Pagar Não Processado

Os campos Saldos Restos a Pagar processado e Saldos Restos a Pagar Não Processado contém a subtração dos valores retidos, entretanto, se observamos o exemplo do caso no Mantis, o campo Valor a Pagar passará a ter uma divergência em relação a fórmula presente atualmente no Portal.

Sendo assim, questiono:

Devemos considerar e aplicar as retenções de valores nos campos Valor Inscrito Processado e Valor Inscrito Não Processado, mantendo a fórmula clássica e apresentando o valor correto do campo Valor a Pagar?
Caso contrário, a divergência não trará questionamentos acerca dos valores apresentados no Portal?

![image](https://user-images.githubusercontent.com/52920939/150006611-7b72894a-2df0-469d-9642-68b1154526a3.png)

**Comment by kesiabomfa** [comment]
Em consulta ao armazém BO para elucidar a dúvida do Luiz, verifiquei a possibilidade de incluir as retenções no valor pago no ano, para que o Portal passa a exibir os valores sem diferença. Dentre as várias opções disponíveis de valores retidos e retenção em Restos a Pagar, o único que trouxe resultados para o empenho 168, foi a Valor Liquidado Retido, os demais valores trouxeram valores zerados.

![image](https://user-images.githubusercontent.com/52920939/150006947-cba3f09c-5fee-4e74-bcd2-ddf537b4476f.png)

**Comment by silviana-faria** [comment]
Especificação #60
