### ISSUE TITLE
Valor 0 para o campo `Número do Contrato` no formulário de detalhamento

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#62]
Mesmo quando essa informação existe, o `Número do Contrato`  na seção `Outras Informações` do formulário de detalhamento está vindo com o valor `0`:

![image](https://user-images.githubusercontent.com/4969445/166822202-166fbf3f-b18f-49dc-80a9-6393f1411aa8.png)

Analisando o caso do contrato 9223570 ([vide info produção](https://www.transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-filtros/5/2019/01-01-2019/31-12-2019/66/64488)), parece que as informações estão sendo inseridas de forma equivocada[^1] na seção de `Dados do Convênio/Parceria de Saída Recursos`

[^1]: Por causa da regra de que 
    > Ao identificar que existe 'Contrato Convênio Saída' relacionado a um empenho deve-se realizar o cruzamento com a base de dados do Pdt consulta Convênio de Saída / Parceria de recursos e caso a informação conste na base de dados essas serão replicadas nesse formulário.

**Comment by silvianafaria** [comment]
Os valores zerados foram corrigidos, porém os dados ainda estão sendo alocados no campo errado

![image](https://user-images.githubusercontent.com/53793354/167692266-c1d9c12e-2eae-4a34-b541-d01b742ba012.png)

**Comment by silvianafaria** [comment]
Dados ainda não corrigidos, os dados do processo de compra não estão sendo exibidos

[Formulário de Detalhamento](https://age7-novo.homologacao.prodemge.gov.br/eventos-extraordinarios/acordo-judicial-reparacao-vale?task=estado_recursosvale.listarEmpenho&ano=2022&dataInicio=01/01/2022&dataFim=31/12/2022&consulta=1&filtro=23&id_projeto=23)

![image](https://user-images.githubusercontent.com/53793354/168303034-1d3011c7-7fe8-4d5e-8cc6-5e63744f495b.png)

**Comment by silvianafaria** [comment]
Dados corrigidos

![image](https://user-images.githubusercontent.com/53793354/171033586-22bee659-5ba9-49e6-bdcb-24099e296149.png)
