### ISSUE TITLE
Valores zerados para a inscrição em restos a pagar no formulário de detalhamento

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#63]
Esse é um exemplo de erro para o empenho 237, emitido em 2011, para o projeto "Fortalecimento e Reestruturação Tecnológica da Controladoria Geral do Estado".

Vide info em [homologação](https://age7-novo.homologacao.prodemge.gov.br/eventos-extraordinarios/acordo-judicial-rompimento-da-barragem-corrego-do-feijao-brumadinho?task=estado_recursosvale.listarEmpenho&ano=&dataInicio=01/01/2022&dataFim=31/12/2022&consulta=1&filtro=76&id_projeto=76):

![image](https://user-images.githubusercontent.com/4969445/166824613-22b8468e-1795-4d5c-8db4-4df5a84b5bf0.png)

versus [produção](https://www.transparencia.mg.gov.br/despesa-estado/restos-a-pagar/restospagar-orgaos/2022/4237/546/42/20/3065/130/493):

![image](https://user-images.githubusercontent.com/4969445/166825091-13cddf60-cb7c-4665-b89c-53c1a4da34a2.png)

Esse empenho de fato foi inscrito em RP.

**Comment by silvianafaria** [comment]
Corrigido

![image](https://user-images.githubusercontent.com/53793354/171033777-1cad73dd-089a-4858-9b46-fc1ee1362067.png)
