### ISSUE TITLE
Mensagens de erro "Cannot reinitialise DataTable"

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#64]
A mensagem de erro

> DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

está acontecendo em múltiplos locais da pesquisa pré-formatada durante acesso ao detalhamento adicional. Segue exemplo para aba `Projetos`

![erro3](https://user-images.githubusercontent.com/4969445/166826754-50f5f8d7-0a3c-49aa-9040-afd81c10a601.gif)

Aparentemente o Portal consegue se recuperar, mas a mensagem é confusa. Depois da mensagem de erro a barra de exibição de linhas duplica:

<img width="1186" alt="20220505T084523" src="https://user-images.githubusercontent.com/4969445/166916757-795e1481-0b23-49cd-9c55-f078d6c24ca0.png">

**Comment by silvianafaria** [comment]
Corrigido
