### ISSUE TITLE
Associação incorreta entre empenho e `Número do Contrato` no formulário de detalhamento

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#67]
Um mesmo processo de compra pode ter múltiplos contratos. Vide por exemplo o processo de compra [1250084 000283/2021](https://www.transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2021/20210101/20211231/360343) da PMMG que possui dois contratos com empenhos distintos:

| numero_empenho|contrato_convenio_saida| valor_despesa_empenhada|
|--------------:|----------------------:|-----------------------:|
|            314|                9316087|                 5096597|
|            317|                9316088|                  640290|

No [ambiente de homologação](https://age7-novo.homologacao.prodemge.gov.br/eventos-extraordinarios/acordo-judicial-rompimento-da-barragem-corrego-do-feijao-brumadinho?task=estado_recursosvale.listarEmpenho&ano=2022&dataInicio=01/01/2022&dataFim=31/12/2022&consulta=1&filtro=62&id_projeto=62) os dois empenhos estão associados ao contrato 9316087:

![20220505T200848](https://user-images.githubusercontent.com/4969445/167041432-86d88be3-3861-4c04-bcde-c0d693940a10.gif)

Não consegui encontrar associação nas tabelas pré-existentes do Portal de Número do Empenho e Número do Contrato, somente entre Número do Empenho e Número do Processo de compra (via `fl_compras_empenho`). Se essa informação não tiver sido inserida no fluxo de dados essa pode ser a explicação.

**Comment by kesiabomfa** [comment]
![image](https://user-images.githubusercontent.com/52920939/167127687-aba53ea1-c0da-4c81-97de-b889f573581c.png)
Para empenhos com mais de um processo de compra ou contrato, tem que aparecer todos.

**Comment by kesiabomfa** [comment]
![image](https://user-images.githubusercontent.com/52920939/167128081-d80196f2-6a30-4a6f-a197-85c2b267155d.png)

**Comment by silvianafaria** [comment]
O número do contrato para o empenho 317 foi representado errado no Pdt

**Comment by kesiabomfa** [comment]
Isso, o contrato do 317 é o 9316088 e o do empenho 314 é o 9316087. Tem que puxar o contratado junto com o processo de compras.

**Comment by fjuniorr** [comment]
As associações estão corretas no [ambiente de homologação](https://age7-novo.homologacao.prodemge.gov.br/eventos-extraordinarios/acordo-judicial-reparacao-vale?task=estado_recursosvale.listarEmpenho&ano=&dataInicio=01/01/2022&dataFim=31/12/2022&consulta=2&filtro=9&id_projeto=9):

### Empenho `314` com contrato `9316087`

![20220512T112836](https://user-images.githubusercontent.com/4969445/168098878-23a0c08c-013b-49c0-9cb2-3f0462d328a2.png)


### Empenho `317` com contrato `9316088`

![20220512T112520](https://user-images.githubusercontent.com/4969445/168098526-ca4c389e-fd3c-4f4a-9ba8-ce606628349a.png)
