### ISSUE TITLE
Cabeçalho fixo não respeita navegação do usuário

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#68]
![20220505T201641](https://user-images.githubusercontent.com/4969445/167042076-deaf7384-2bc6-4834-a11a-15bf9feb82e7.gif)

**Comment by silvianafaria** [comment]
Cabeçado corrigido


![20220510_145802](https://user-images.githubusercontent.com/53793354/167692615-32f243e3-5b67-4896-bec5-cc12cb48ecb7.gif)
