### ISSUE TITLE
Processos de compra sem contratos não são demonstrados no formulário de detalhamento

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#70]
Nem todos os processos de compra possuem contratos associados. Um exemplo é o processo de compra [1081017 000086/2021](https://www.transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-procedimento/3/2021/01-01-2021/31-12-2021/1831099/0/0/68088/0/0/0/0/13164/61100196/273158/1805096/358920/1081017000086-2021) que não possui contrato, mas possui empenho associado a esse contrato. 

Essa informação deveria estar demonstrada na seção de `Dados do Processo de Compra` do formulário de detalhamento. Vide contexto no video abaixo:

https://www.loom.com/share/8d3a8793a8af48a1af734c0eedae6292

A informação do processo de compra está disponível no Armazém SIAFI na variável

![20220511T161537](https://user-images.githubusercontent.com/4969445/167928626-53dbcaf5-ca2a-4c6c-a770-f3691a96dd54.png)

mas aparentemente não está nas bases do Portal. Digo isso porque não encontrei o processo 1081017 000086/2021 (id_processo = 358920) na tabela `fl_compras_empenho`.

**Comment by fjuniorr** [comment]
Atualizando o entendimento, esse processo parece ter sido criado duas vezes pela AGE com o mesmo objeto, o [1081017 000086/2021](https://www.transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2021/20210101/20211231/358920) e o [1081017 000091/2021](https://www.transparencia.mg.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2021/20210101/20211231/359997), mas o último que foi efetivamente utilizado para fins de execução:

![20220512T154721](https://user-images.githubusercontent.com/4969445/168146940-bd73a017-a19a-4832-ae02-fc4eff1ba327.png)

A associação entre empenho e processo de compra existe na `fl_compras_empenho`, so não está representado no ambiente de homologação.

**Comment by silvianafaria** [comment]
Corrigido

https://user-images.githubusercontent.com/53793354/170559403-276e10c5-e04a-4d4a-ad75-18745a34aa3e.mp4
