### ISSUE TITLE
Link do `Compartilhar > Copiar Link` não abre formulário de detalhamento em novo acesso

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#72]
O link proveniente da funcionalidade de `Copiar Link` do formulário de detalhamento deveria direcionar para o formulário de detalhamento em um novo acesso mas isso não está ocorrendo.

Vide exemplo [deste link](https://age7-novo.homologacao.prodemge.gov.br/eventos-extraordinarios/acordo-judicial-rompimento-da-barragem-corrego-do-feijao-brumadinho?task=estado_recursosvale.listarEmpenho&ano=&dataInicio=01/01/2022&dataFim=31/12/2022&consulta=2&filtro=27&id_projeto=27) no video:

https://www.loom.com/share/d0ccc740071d4ea7ab902ea95817c64c

**Comment by silvianafaria** [comment]
Não corrigido

**Comment by silvianafaria** [comment]
Dados corrigidos
