### ISSUE TITLE
Nome incorreto para seção `Dados do Processo de Compra` no formulário de detalhamento

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#73]
A seção `Dados do Processo de Compra` na aba `Outras Informações` do formulário de detalhamento está com o nome de `Detalhamento do Pagamento`:

![20220512T113128](https://user-images.githubusercontent.com/4969445/168100222-3cf41457-6603-421c-a307-0c2feb89fc50.png)

### Links

- [Spec](https://github.com/transparencia-mg/especificacoes-portal-transparencia/blob/master/espec018_recursos-acordo-judicial-vale/especifica%C3%A7%C3%A3o/recursos-vale-espec.md#campos-do-formul%C3%A1rio-de-detalhamento)
- [Exemplo](https://age7-novo.homologacao.prodemge.gov.br/eventos-extraordinarios/acordo-judicial-reparacao-vale?task=estado_recursosvale.listarEmpenho&ano=&dataInicio=01/01/2022&dataFim=31/12/2022&consulta=2&filtro=9&id_projeto=9)

**Comment by silvianafaria** [comment]
Não corrigido 
![image](https://user-images.githubusercontent.com/53793354/170764680-41ed0982-80f6-4068-8036-cefbe624d1f3.png)

**Comment by silvianafaria** [comment]
Corrigido
![dad](https://user-images.githubusercontent.com/53793354/173369813-beb5329a-5983-4aa4-bded-03af455e07b3.png)
