### ISSUE TITLE
Horizonte de cobertura dos valores na barra de filtro vertical

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/especificacoes-portal-transparencia#75]
O empenho 227 da CGE está associado ao processo de compra [1521001 000025/2021](https://age7-novo.homologacao.prodemge.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-detalhe-proccompra/2021/20210101/20211231/1367833) e ao contrato [9293571](https://age7-novo.homologacao.prodemge.gov.br/compras-e-patrimonio/compras-e-contratos/comprasecontratos-filtros/5/2021/01-01-2021/31-12-2021/564/610196) de 2021. O processo de compra aparece na barra vertical de filtros e o contrato não aparece. 

__Isso é um erro__.

Um caso similar acontece para o empenho 237 da CGE que está associado ao processo de compra 1521001 000024/2019 e ao contrato 9223570 também de 2019. Enquanto o processo de compra aparece na barra vertical de filtros, o contrato não aparece. 

Nesse caso, precisamos clarificar qual o comportamento  está sendo aplicado para determinar se os valores de determinado campo vão aparecer ou não na barra de filtros vertical

O vídeo abaixo exemplifica essa situação:

https://www.loom.com/share/2d917653af2e48289b6a72cc9b413ec3

**Comment by silvianafaria** [comment]
**Ainda ocorre divergências**:

**_VÍDEO 1_** 
![horizonte-cobertura](https://user-images.githubusercontent.com/53793354/174620580-21bcf935-c7e2-4cbc-a1c3-d42ca1cf3910.gif)

-----------------------------------------------------------------------------------------------------------------------------
**_VÍDEO 2_** 
![horizonte-cobertura2](https://user-images.githubusercontent.com/53793354/174621218-f474bf1a-a902-4356-8de7-965f06c9f6ba.gif)

**Comment by silvianafaria** [comment]
Dados corrigidos. verificando apenas o contratos CGE

![filtro-vertical](https://user-images.githubusercontent.com/53793354/183923162-2ad01c16-071b-45f8-ad10-4c0dd2ed4502.gif)
